---
swagger: "2.0"
info:
  title:
    Fn::Sub: commit-on-release-${ENVIRONMENT}
  description: Release-subscription API
  contact:
    name: Joakim Hedlund
  version: 1.0.0
servers:
  - url: https://aws.triplehead.net/commit-on-release/
    description: The best of servers.
schemes:
  - https

x-definitions:
  AWSLambda: &AWSLambda
    x-amazon-apigateway-integration:
      uri:
        Fn::Sub: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${ApiLambda.Arn}/invocations
      passthroughBehavior: when_no_match
      httpMethod: POST
      type: aws_proxy

paths:
  /release:
    post:
      <<: *AWSLambda
      summary: Endpoint for newreleases.io webhooks
      consumes:
        - application/json
      parameters:
        - name: event
          in: body
          required: true
      responses:
        200:
          description: maximum swag
        400:
          description: no bueno

x-amazon-apigateway-request-validator: validate-body-and-params
x-amazon-apigateway-request-validators:
  validate-body-and-params:
    validateRequestParameters: true
    validateRequestBody: true
x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:  &gatewayCorsResponse
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,GET,POST'"
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
  DEFAULT_5XX: *gatewayCorsResponse